<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Careers</name>
   <tag></tag>
   <elementGuidId>71e4a7da-e18e-43fe-b494-48bcd397e454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-mainnavigation']/div/div/div/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.tb-megamenu-item.level-1.mega.mega-align-justify.dropdown.open.animating > a.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a4de9286-71c0-4445-90e2-a9e2dac86db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/careers/</value>
      <webElementGuid>87a833eb-b392-4c0b-acfc-f4613db6d8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>a4cd7037-8251-47cf-92ef-67eeb2529a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52fe8042-e925-4afc-80cc-a7c880fe9702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Careers
          
          </value>
      <webElementGuid>129aacb4-55a4-4205-ad87-1dae2aeefbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-mainnavigation&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;tb-megamenu tb-megamenu-main&quot;]/div[@class=&quot;nav-collapse always-show&quot;]/ul[@class=&quot;tb-megamenu-nav nav level-0 items-7&quot;]/li[@class=&quot;tb-megamenu-item level-1 mega mega-align-justify dropdown open animating&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>ce521596-cbbc-42e7-82ee-ac675f9b440a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-mainnavigation']/div/div/div/ul/li[5]/a</value>
      <webElementGuid>6c9b38fc-f5ef-46e5-8746-a0816fc06c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Careers')]</value>
      <webElementGuid>488b4dd8-39fb-4924-b805-7fd760ac77dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read More'])[4]/following::a[1]</value>
      <webElementGuid>4a8e06fe-a8d8-4224-a132-cdc678d1202f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured Event'])[1]/following::a[2]</value>
      <webElementGuid>78bba2cf-4d24-4eb1-96e6-a8f6fe50e270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[2]/preceding::a[1]</value>
      <webElementGuid>a003e72b-3067-46e3-939a-41b4bb30cf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why TechM'])[1]/preceding::a[1]</value>
      <webElementGuid>0074adde-0d8a-4ef6-a25b-e19f1ec7d3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Careers']/parent::*</value>
      <webElementGuid>bd9d3a93-7439-4534-a46f-1a5568da6886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/careers/')]</value>
      <webElementGuid>45333e42-58ab-4a05-b01b-52d6e81d5ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>d804afb3-7c17-403d-b95a-c44137d55f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/careers/' and (text() = '
          Careers
          
          ' or . = '
          Careers
          
          ')]</value>
      <webElementGuid>b2a1e09f-cd8f-43e8-bbad-ae696bbcdf41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
