<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IFRAME-CAPTCHA</name>
   <tag></tag>
   <elementGuidId>cdb89c4b-79d0-48a1-a22f-82a088f28c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/section[13]/div/div[2]/div/form/div[4]/div/div/div/div/div/div/iframe[count(. | //*[@title = 'reCAPTCHA']) = count(//*[@title = 'reCAPTCHA'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>6c84a017-623f-4b0a-be39-10b886744ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/section[13]/div/div[2]/div/form/div[4]/div/div/div/div/div/div/iframe</value>
      <webElementGuid>cb933a4d-6463-44da-9b76-e2cf254849a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
