<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Capabilities</name>
   <tag></tag>
   <elementGuidId>b10ada6a-ccce-42bf-bb78-728bad3877e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-mainnavigation']/div/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.tb-megamenu-item.level-1.mega.mega-align-justify.dropdown.open.animating > a.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04351fae-ebd8-431c-8d38-204c0e575e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/our-capabilities/</value>
      <webElementGuid>d9ea5616-4ac9-466a-83eb-cf746a411e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>094797ce-da73-4d24-b1f8-4bc5357fb38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7519ea7f-656b-424b-ae4f-d64db4e0a00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Capabilities
          
          </value>
      <webElementGuid>506cf01a-6940-407c-9cad-3800ac42ab72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-mainnavigation&quot;)/div[@class=&quot;content&quot;]/div[@class=&quot;tb-megamenu tb-megamenu-main&quot;]/div[@class=&quot;nav-collapse always-show&quot;]/ul[@class=&quot;tb-megamenu-nav nav level-0 items-7&quot;]/li[@class=&quot;tb-megamenu-item level-1 mega mega-align-justify dropdown open animating&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>44f7e1dc-e31a-41d9-b7bc-63a65a1b776e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-mainnavigation']/div/div/div/ul/li[2]/a</value>
      <webElementGuid>fa51da63-2210-4bb3-84c4-7113b97f14e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Capabilities')]</value>
      <webElementGuid>0c6459de-9147-4d74-9cd0-7a4178558955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[2]/following::a[1]</value>
      <webElementGuid>078eb305-d342-45de-9ad0-b13134515582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Indus Project'])[1]/following::a[2]</value>
      <webElementGuid>33a1cb17-e8a4-440d-a3ac-dcc364691157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Services'])[1]/preceding::a[1]</value>
      <webElementGuid>e90f96e8-2cd6-42d6-84ab-a2855a51d06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strategy &amp; Consulting'])[1]/preceding::a[1]</value>
      <webElementGuid>bf353913-ac0b-43d8-b666-13c2dcaeca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Capabilities']/parent::*</value>
      <webElementGuid>8df2466a-0eb6-4ea6-907b-5a8690a8d817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/our-capabilities/')]</value>
      <webElementGuid>a48451f1-042f-442f-ad3f-5152e7c79cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>d510b659-71ec-4fbf-a7d2-8ccd0d836025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/our-capabilities/' and (text() = '
          Capabilities
          
          ' or . = '
          Capabilities
          
          ')]</value>
      <webElementGuid>56c3c92a-89a2-4011-b726-87913e74b41e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
