<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>COMPANY_DROPDOWN</name>
   <tag></tag>
   <elementGuidId>eca79ada-0643-4c87-885f-dccaa84185b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='company']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#company</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>86b4ec3a-d7c9-4ef7-8d81-274db8fd27b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>81537f5d-8542-4021-a36a-85d4756edf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>company</value>
      <webElementGuid>f931fba9-bfa2-4b56-8483-bfe8ad0cb185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics</value>
      <webElementGuid>33c48788-698e-4779-a607-2e6515d60e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company&quot;)</value>
      <webElementGuid>574094b8-1d84-4f21-9f6d-ebd1b33461bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='company']</value>
      <webElementGuid>726921bc-6b65-4356-aff2-0eb23332b7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[4]/div/select</value>
      <webElementGuid>379ba7c4-b164-4b76-aa23-9df78b995b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::select[1]</value>
      <webElementGuid>e1c2014b-530d-43d2-aedd-907c0dcd24b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>3075e691-f72a-4407-9917-79baa8f07101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>36fef9aa-8fe0-41b4-af76-b2202b41f977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'company' and @name = 'company' and (text() = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics' or . = '-- Choose a company --Apple Inc.Thinking MachinesRCANetronicsTandy CorporationCommodore InternationalMOS TechnologyMicro Instrumentation and Telemetry SystemsIMS Associates, Inc.Digital Equipment CorporationLincoln LaboratoryMoore School of Electrical EngineeringIBMAmiga CorporationCanonNokiaSonyOQONeXTAtariAcorn computerTimex SinclairNintendoSinclair Research LtdXeroxHewlett-PackardZemmixACVSSanyoCrayEvans &amp; SutherlandE.S.R. Inc.OMRONBBN TechnologiesLenovo GroupASUSAmstradSun MicrosystemsTexas InstrumentsHTC CorporationResearch In MotionSamsung Electronics')]</value>
      <webElementGuid>da89f123-4216-4666-8ef1-3c1f2958659b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
