<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FILTER_BY_NAME_BUTTON</name>
   <tag></tag>
   <elementGuidId>ba6d0a9b-993b-4112-bc67-e2425b12d381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchsubmit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchsubmit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2529f74-5762-4127-a49f-771c887476a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a39117eb-1f89-4bf9-8eee-d33ca86e65a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchsubmit</value>
      <webElementGuid>f2ecfb90-b3c6-4638-91bc-5c9ea117d6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Filter by name</value>
      <webElementGuid>bdacb7e0-4037-4b31-8ce8-89bdb6a17fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn primary</value>
      <webElementGuid>5ae36515-cc8a-49a7-a10a-443ad2b9717e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchsubmit&quot;)</value>
      <webElementGuid>15cd5710-5d9d-4b20-86d8-bcb5d6bdbdaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchsubmit']</value>
      <webElementGuid>564ba1cf-79cd-41d4-bf1d-339c5afc4198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions']/form/input[2]</value>
      <webElementGuid>049398e5-3d0b-4bed-a1da-dc8eb8afcb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>9e0fd739-c05e-4ddf-a899-f97c0113df19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'searchsubmit']</value>
      <webElementGuid>bc87b35d-3400-45f5-8112-6fec5b7529ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
