<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>INTRODUCED-DATE</name>
   <tag></tag>
   <elementGuidId>e4cc9b4e-84e0-4202-aeda-aeea2ed9816b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='introduced']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#introduced</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab8c9436-2a61-47b0-b1c1-bc34e865e766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4d625e0-6c12-4189-8556-09ebf28466c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>introduced</value>
      <webElementGuid>1f283901-0ff7-445c-824c-3b8be29bae37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>introduced</value>
      <webElementGuid>18074b41-eca6-4da3-ba28-70d9dce2ea79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;introduced&quot;)</value>
      <webElementGuid>8ccf922f-8c3d-496b-ac5a-8e367c5d78c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='introduced']</value>
      <webElementGuid>6e7a540f-6284-476d-ad18-2ecb7e7e4c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/form/fieldset/div[2]/div/input</value>
      <webElementGuid>33f0f503-ae9c-4141-ad6f-edd5ffd4d7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5923bbef-b77f-419b-b0dc-9c236dd5b0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'introduced' and @name = 'introduced']</value>
      <webElementGuid>eba9b893-0514-4eaa-88d8-e44911467f6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
